config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  # Websockets resemble this URL
  mount ActionCable.server => '/cable'
  resources :order_details
  resources :orders
  post 'groups/members', to: 'groups#members'
  post 'groups/add_member', to: 'groups#add_member'
  get 'friends', to: 'friends#index'
  post 'friends', to: 'friends#create'
  put 'friends/:id/accept', to: 'friends#accept'
  delete 'friends/:id/decline', to: 'friends#decline'
  get 'friends/:id/show', to: 'friends#show'
  delete 'friends/:id/remove', to: 'friends#remove'
  devise_for :users
  # resources :users
  root 'users#index'
  # resources :groups
  resources :groups do
  member do
    get 'members'
  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :user
  belongs_to :order
end

app/controllers/order_details_controller.rb
class OrderDetailsController < ApplicationController
  before_action :set_order_detail, only: [:show, :edit, :update, :destroy]

  # GET /order_details
  # GET /order_details.json
  def index
    @order_details = OrderDetail.all
  end

  # GET /order_details/1
  # GET /order_details/1.json
  def show
  end

  # GET /order_details/new
  def new
    @order_detail = OrderDetail.new
  end

  # GET /order_details/1/edit
  def edit
  end

  # POST /order_details
  # POST /order_details.json
  def create
    @order_detail = OrderDetail.new(order_detail_params)
    respond_to do |format|
      if @order_detail.save
        format.html { redirect_to @order_detail.order, notice: 'Order detail created.' }
        format.json { render :show, status: :created, location: @order_detail }
      else
        format.html { render :new }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_details/1
  # PATCH/PUT /order_details/1.json
  def update
    respond_to do |format|
      if @order_detail.update(order_detail_params)
        format.html { redirect_to @order_detail.order, notice: 'Order detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_detail }
      else
        format.html { render :edit }
        format.json { render json: @order_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_details/1
  # DELETE /order_details/1.json
  def destroy
    @order_detail.destroy
    respond_to do |format|
      format.html { redirect_to @order_detail.order, notice: 'Order detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_detail
      @order_detail = OrderDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_detail_params
      params.require(:order_detail).permit(:user_id, :order_id, :item, :amount, :price, :comment)
    end
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/views/order_details/_form.html.erb
<%= form_for(order_detail) do |f| %>
  <% if order_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_detail.errors.count, "error") %> prohibited this order_detail from being saved:</h2>

      <ul>
      <% order_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :order_id %>
    <%= f.text_field :order_id %>
  </div>

  <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_details/edit.html.erb
<h1>Editing Order Detail</h1>

<%= render 'form', order_detail: @order_detail %>

<%= link_to 'Show', @order_detail %> |
<%= link_to 'Back', order_details_path %>

app/views/order_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Details</h1>

<table class="table table-striped table-bordered"> 
  <thead>
    <tr>
      <th>User</th>
      <th>Order</th>
      <th>Item</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_details.each do |order_detail| %>
      <tr>
        <td><%= order_detail.user %></td>
        <td><%= order_detail.order %></td>
        <td><%= order_detail.item %></td>
        <td><%= order_detail.amount %></td>
        <td><%= order_detail.price %></td>
        <td><%= order_detail.comment %></td>
        <td><%= link_to 'Show', order_detail %></td>
        <td><%= link_to 'Edit', edit_order_detail_path(order_detail) %></td>
        <td><%= link_to 'Destroy', order_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Detail', new_order_detail_path %>

app/views/order_details/new.html.erb
<h1>New Order Detail</h1>

<%= render 'form', order_detail: @order_detail %>

<%= link_to 'Back', order_details_path %>

app/views/order_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order_detail.user %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_detail.order %>
</p>

<p>
  <strong>Item:</strong>
  <%= @order_detail.item %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @order_detail.amount %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order_detail.price %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @order_detail.comment %>
</p>

<%= link_to 'Edit', edit_order_detail_path(@order_detail) %> |
<%= link_to 'Back', order_details_path %>