config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  # Websockets resemble this URL
  mount ActionCable.server => '/cable'
  resources :order_details
  resources :orders
  post 'groups/members', to: 'groups#members'
  post 'groups/add_member', to: 'groups#add_member'
  get 'friends', to: 'friends#index'
  post 'friends', to: 'friends#create'
  put 'friends/:id/accept', to: 'friends#accept'
  delete 'friends/:id/decline', to: 'friends#decline'
  get 'friends/:id/show', to: 'friends#show'
  delete 'friends/:id/remove', to: 'friends#remove'
  devise_for :users
  # resources :users
  root 'users#index'
  # resources :groups
  resources :groups do
  member do
    get 'members'
  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
#
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :members, class_name: 'User',
                                    foreign_key: 'group_id',
                                    join_table: :groups_members
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i(show edit update destroy)

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.groups
  end

  def show
    @user = current_user
    @groups = Group.find params[:id]
    @membersG= @group.members
   end

  def new
    @user = current_user
    @group = @user.groups.new
  end

  def edit; end

  def create
    @user = current_user
    @group = @user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user
    @group = @user.groups.find(params[:id])
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to [@group], notice: 'Group updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def members
    @group = Group.find params[:group_ID]
    # @group = Group.where(:group_group_ID => params[:group_ID]).first # file_name is the data key of Ajax request in view
    @members = @group.members
  #  if request.xhr?
   #
  #      render :json => {
  #                          :g_members => @group.members
  #                      }
  #   end
    respond_to do |format|
      # format.html # show.html.erb
      format.json { render json: @members.to_json }
    end
  end

  def add_member
    begin
      @member = current_user.friends.where(email: params[:friend_email]).first
      @group = Group.find params[:group_id]
      begin
        @group.members.find @member.id
      rescue
        @group.members << @member
      end
      respond_to do |format|
        # format.html # show.html.erb
        format.json { render json: @member }
      end
    rescue
      respond_to do |format|
        # format.html # show.html.erb
        format.json { render json: "Not found" }
      end
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @user = current_user
    @group = @user.groups.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name, :user_id)
  end
  def member_params
    params.require(:group).permit(:name, :user_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for([@group]) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

    <%= f.hidden_field :user_id %>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', [@group] %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>
<div>
    <%= form_for([current_user.groups.build]) do |f| %>
    <%= f.hidden_field :user_id, value:current_user.id %>
    <table style="margin:0 auto;">
        <tr>
            <td>
                <h4>New Group:</h4>
            </td>
            <td><%= f.text_field :name, placeholder:'Enter group name' %></td>
            <td>
                <%= f.submit class: "btn btn-success", value:'Add' %></td>
        </tr>
    </table>

    <% end %>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <div class="card card-default">
                <div class="card-header center">
                    <h4>My Groups</h4>
                </div>
                <div class="card-block scrollable" >
                    <table class="table table-striped table-bordered">
                        <tbody>
                            <% @groups.each do |g| %>
                                <% if g.id != nil %>
                                    <tr>
                                        <td class='g_name' style="cursor:pointer;">
                                            <label style="cursor:pointer;" val='<%="#{g.id}"%>'><%="#{g.name }"%></label>
                                        </td>
                                        <td><%= link_to 'Delete', g, method: :delete, data: { confirm: 'Are you sure?' },class: "text-danger" %></td>
                                    </tr>
                                <% end %>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="card card-default">
                <div class="card-header center">
                    <h4>Group Members</h4>
                </div>
                <div class="card-block scrollable">
                    <%= form_tag("/groups/add_member", method: :post, remote: true) do %>
                    <table style="margin:0 auto;">
                        <tr>
                            <td class="h6"><%= label_tag(:friend_email, "Add Friend to group:")%></td>
                            <td><%= hidden_field_tag :group_id%></td>
                            <td><%= text_field_tag :friend_email, nil,placeholder:'Enter friend email'%></td>
                            <td><%= submit_tag :Add, class: "btn btn-success" %></td>
                        </tr>
                    </table>
                    <% end %>

                    <div>
                      <ul id="tst" class="list-group">
                      </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

<br>

<!-- <%= link_to 'New Group', new_group_path %> -->

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group Admin:</strong>
  <%= @group.name %>
</p>
  <strong>Group Mambers:</strong> <br>
<% @membersG.each do |m| %>
<%= m.name %> <br />
<% end %>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>