config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  # Websockets resemble this URL
  mount ActionCable.server => '/cable'
  resources :order_details
  resources :orders
  post 'groups/members', to: 'groups#members'
  post 'groups/add_member', to: 'groups#add_member'
  get 'friends', to: 'friends#index'
  post 'friends', to: 'friends#create'
  put 'friends/:id/accept', to: 'friends#accept'
  delete 'friends/:id/decline', to: 'friends#decline'
  get 'friends/:id/show', to: 'friends#show'
  delete 'friends/:id/remove', to: 'friends#remove'
  devise_for :users
  # resources :users
  root 'users#index'
  # resources :groups
  resources :groups do
  member do
    get 'members'
  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
#
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  has_many :participated_users, through: :order_details,
                                class_name: 'User',
                                foreign_key: 'user_id'
  has_and_belongs_to_many :invited_users, class_name: 'User',
                                          foreign_key: 'order_id',
                                          join_table: :invitees_orders
  has_attached_file :menu_img,
                    styles: { medium: '300x300>', thumb: '100x100>' },
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :menu_img, content_type: %r{\Aimage\/.*\z}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_user.orders.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = current_user.orders.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = current_user.orders.new(order_params)
    # @member = current_user.friends.where(id: params[:f.id]).first

    # respond_to do |format|
    if @order.save
      begin
        params[:invited_users].each do |u_id|
          @member = current_user.friends.find u_id.to_i
          @order.invited_users << @member
          notif_body = current_user.name << ' invited you to order ' << @order.order_type
          link_body = "/orders/#{@order.id}"
          @member.notifications.create(user_id: @member.id, event: notif_body, link: link_body)
        end
      rescue
        begin
          params[:invited_groups].each do |g_id|
            @group = current_user.groups.find g_id.to_i
            @group.members.each do |group_member|
              begin
                @order.invited_users.find group_member
              rescue
                @order.invited_users << group_member
                notif_body = current_user.name << ' invited you to order ' << @order.order_type
                link_body = "/orders/#{@order.id}"
                group_member.notifications.create(user_id: group_member.id, event: notif_body, link: link_body)
              end
            end
          end
        rescue

        end
      end
      respond_to do |format|
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        # format.json { render json: @order.invited_users }
      end
      # format.html { redirect_to @order, notice: 'Order was successfully created.' }
      # format.json { render :show, status: :created, location: @order }
      #   else
      #     format.html { render :new }
      #     format.json { render json: @order.errors, status: :unprocessable_entity }
    end
    # end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    @order = current_user.orders.find(params[:id])
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def add_order
    begin
      @member = current_user.friends.where(id: params[:friend_id]).first
      @order = Order.find params[:g.id]
      begin
        @order.invited_users.find @member.id
      rescue
        @order.invited_users << @member
      end
      respond_to do |format|
        # format.html # show.html.erb
        format.json { render json: @member }
      end
    rescue
      respond_to do |format|
        # format.html # show.html.erb
        format.json { render json: "Not found" }
      end
    end


  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:order_type, :resturant_name, :user_id, :menu_img)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= simple_form_for @order, remote: true do |f| %>
<% if @order.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@order.errors.count, "error") %>
        prohibited this order from being saved:</h2>

    <ul>
        <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :order_type, 'Choose order type:' %>
    <%= f.select :order_type, [['Dinner', 'Dinner'], ['Launch', 'Launch'],
     ['break fast', 'break fast']] %>
</div>
<br>
<div class="field">
    <%= f.text_field :resturant_name, :placeholder => 'Enter Restaurant Name' %>
</div>

<div class="field">
    <label class="btn btn-success btn-file"> Choose Menu image
      <%= f.file_field :menu_img,style: "display: none;" %>
    </label>
</div>
<div class="field">
    <%=f.input :invited_users do%>
        <% current_user.friends.each do |f| %>
            <%= check_box_tag 'invited_users[]', f.id %>
            <%= h f.name%>
        <%end%>
    <%end%>
</div>
<div class="field">
    <%=f.input :invited_groups do%>
        <% current_user.groups.each do |g| %>
            <%= check_box_tag 'invited_groups[]', g.id %>
            <%= h g.name%>
        <%end%>
    <%end%>
</div>
<%= f.hidden_field :user_id %>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<div class="actions">
    <%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 push-md-2 col-lg-8 push-lg-2">
<div class="card card-default">
<div class="card-header center">
  <h4>Orders</h4>
</div>
<div class="card-block scrollable">
  <table class="table table-striped table-bordered">
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to "#{order.order_type}", order, class: "text-primary"%> <%=" from #{order.resturant_name} on #{order.created_at}"%></td>
          <td><%= link_to 'Delete', order,class: "text-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>
</div>
</div>

<div class="center">
  <%= button_to 'New Order', new_order_path,method: :get, class: "btn btn-success" %>
</div>

app/views/orders/new.html.erb
<div class="center" style="margin-top:10px;">
  <h3>Add New Order</h3>
</div>
<div class="border-form-div center" style="margin-top:30px;">
  <%= render 'form', order: @order %>

  <%= link_to 'Back', orders_path %>
</div>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-8 push-md-2 col-lg-8 push-lg-2">
            <div class="card card-default">
                <div class="card-header center">
                    <h4><%= "Order for #{@order.order_type} by " %><%= link_to "#{@order.user.name}","/friends/#{@order.user.id}/show", class: "text-primary"%></h4>
                </div>
                <div class="card-block">
                    <%= image_tag @order.menu_img.url,class: "img-fluid" %>
                </div>
            </div>
        </div>
        <div class="col-sm-10 push-sm-1" style="margin-top:10px;">
            <div class="card card-default">
                <div class="card-header center">
                    <h4>Order details</h4>
                </div>
                <div class="card-block scrollable" >
                    <table class="table table-striped table-bordered">
                        <tr>
                            <th>Name</th>
                            <th>Item</th>
                            <th>Amout</th>
                            <th>Price</th>
                            <th>Comment</th>
                            <th>Action</th>
                        </tr>
                        <% @order.order_details.each do |order_detail| %>
                        <tr>
                            <td><%= order_detail.user.name %></td>
                            <td><%= order_detail.item %></td>
                            <td><%= order_detail.amount %></td>
                            <td><%= order_detail.price %></td>
                            <td><%= order_detail.comment %></td>
                            <td><%= link_to('Edit', edit_order_detail_path(order_detail), class: "text-primary") if order_detail.user.id==current_user.id %>
                                <%= link_to('Delete', order_detail, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger")if order_detail.user.id==current_user.id %></td>

                        </tr>
                        <% end %>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-sm-10 push-sm-1" style="margin-top:10px;">
            <div class="card card-default">
                <div class="card-header center">
                    <h4>Add a detail:</h4>
                </div>
                <div class="card-block">

                    <%= form_for([@order.order_details.build]) do |f| %>
                    <%= f.hidden_field :user_id, value:current_user.id %>
                    <%= f.hidden_field  :order_id %>
                    <table class="table table-striped table-bordered">
                        <tr>
                            <th>
                                <%= f.label :item %></th>
                            <th>
                                <%= f.label :amount %></th>
                            <th>
                                <%= f.label :price %></th>
                            <th>
                                <%= f.label :comment %></th>
                        </tr>
                        <tr>
                            <td><%= f.text_field :item %></td>
                            <td><%= f.number_field :amount %></td>
                            <td><%= f.text_field :price %></td>
                            <td><%= f.text_area :comment %></td>
                        </tr>
                        <tr>
                            <td colspan="4">
                                <%= f.submit value:"Add to order", class: "btn btn-success" %></td>
                        </tr>
                    </table>

                    <% end %>

                </div>
            </div>
        </div>
    </div>
</div>