config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  # Websockets resemble this URL
  mount ActionCable.server => '/cable'
  resources :order_details
  resources :orders
  post 'groups/members', to: 'groups#members'
  post 'groups/add_member', to: 'groups#add_member'
  get 'friends', to: 'friends#index'
  post 'friends', to: 'friends#create'
  put 'friends/:id/accept', to: 'friends#accept'
  delete 'friends/:id/decline', to: 'friends#decline'
  get 'friends/:id/show', to: 'friends#show'
  delete 'friends/:id/remove', to: 'friends#remove'
  devise_for :users
  # resources :users
  root 'users#index'
  # resources :groups
  resources :groups do
  member do
    get 'members'
  end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>YallaNotlob</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <div class="container fluid">
            <% if user_signed_in?%>
            <div class="panel panel-default" style="background-color: white; padding: 20px; border-radius: 10px; margin-top: 40px; min-height: 80vh;">
                <div class="panel-body">
                    <% @notifications = current_user.notifications.reverse%>
                    <div style="text-align: center;">
                        <span class="h1">Yalla Notlob</span>
                    </div>
                    <div class="btn-group" role="group" aria-label="...">
                        <%= button_to 'Home', "/", method: :get ,class: "btn btn-primary"%>
                        <%= button_to 'Friends', friends_path, method: :get ,class: "btn btn-primary"%>
                        <%= button_to 'Groups', groups_path, method: :get ,class: "btn btn-primary"%>
                        <%= button_to 'Orders', orders_path, method: :get ,class: "btn btn-primary"%>
                    </div>
                    <div class="btn-group" role="group" aria-label="..." id="logout">
                        <%= render "notifications/notification_center", notifications: @notifications %>
                        <%= button_to 'Logout', destroy_user_session_path, method: :delete ,class: "btn btn-default"%>
                    </div>
                    <% end %>
                    <!-- <p id="notice"><%= notice %></p> -->
                    <!-- <p class="alert"><%= alert %></p> -->
                    <%= yield %>
                    <% if user_signed_in? %>
                </div>
            </div>
            <% end %>
        </div>
    </body>
</html>